[workspace]
resolver = "2"
members = [
    "nebula",
    "programs/orion_nebula",
    "programs/orion_native",
    "integration_tests",
]

[workspace.dependencies]

nebula = { path = "nebula" }

solana-program = "2"
solana-program-test = "2"
solana-sdk = "2"
tokio = "*"
