[workspace]
resolver = "2"
members = ["nebula", "programs/orion_nebula", "integration_tests"]

[workspace.dependencies]

nebula = { path = "nebula" }

solana-program = "1"
solana-program-test = "1"
solana-sdk = "1"
solana-client = "1"
bytemuck = "1"
thiserror = "*"
borsh = "*"

tokio = "*"
