[package]
name = "nebula"
version = "0.1.0"
edition = "2021"

[dependencies]

solana-program.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
borsh.workspace = true
sha2-const.workspace = true
static_assertions.workspace = true
